name: Selenium Tests with Allure Report
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Run Selenium tests headless
      run: mvn test -Dbrowser=chrome_headless -Dsurefire.useFile=false
    - name: Print dump files
      if: always()
      run: find . -name "*.dumpstream" -exec cat {} \;
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: surefire-reports
        path: target/surefire-reports/
        retention-days: 30